@startuml
title Основной рабочий процесс

start

:Пользователь открывает программу;
:Инициализация базы данных;

while (Работа с программой) is (Да)
    :Отображение главного меню;
    if (Выбор пользователя?) then (Управление консолями)
        :Открытие меню консолей;
    elseif (Управление аксессуарами)
        :Открытие меню аксессуаров;
    elseif (Управление клиентами)
        :Открытие меню клиентов;
    elseif (Управление заказами)
        :Открытие меню заказов;
    else (Выход)
        stop
    endif
endwhile

stop
@enduml