@startuml
left to right direction
actor "Администратор" as A
actor "Клиент" as C

A --> (Управление_консолями)
A --> (Управление_аксессуарами)
A --> (Управление_клиентами)
A --> (Управление_заказами)

C --> (Просмотр_ассортимента)
C --> (Оформление_заказа)

(Управление_консолями) .> (Добавление_консоли) : include
(Управление_консолями) .> (Редактирование_консоли) : include
(Управление_консолями) .> (Удаление_консоли) : include

(Управление_заказами) .> (Добавление_позиции) : include
(Управление_заказами) .> (Удаление_позиции) : include

note right of (Управление_аксессуарами)
  Управление аксессуарами
  для игровых консолей
end note
@enduml